site_name: Moje Portfolio AI
site_author: Mirosław Baczkowski
site_description: Portfolio moich projektów oraz analiz.
site_url: https://miroslaw7224.github.io/My_Ai_Portfolio/
repo_name: Miroslaw7224/My_Ai_Portfolio
repo_url: https://github.com/Miroslaw7224/My_Ai_Portfolio
docs_dir: docs
site_dir: site
use_directory_urls: true
theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tracking
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.annotate
    - content.tabs.link
    - content.image.zoom
  palette:
    - scheme: slate
      primary: black
      accent: cyan
  font:
    text: Exo 2
    code: Share Tech Mono
  icon:
    logo: material/brain
  custom_dir: overrides


nav:
  - "// init": index.md
  - "// projekty": obecne-projekty.md
  - "// portfolio":
    - "Code Sensei": projects/Code_sensei/code_sensei.md
    - "Titanic": projects/Titanic/index.md
    - "Iris": projects/Iris/index.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
